name: Update Fork on New Release

on:
  schedule:
    - cron: "0 0 * * *"
  workflow_dispatch:

permissions:
  contents: write

jobs:
  sync:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout fork
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Set up Git
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "41898282+github-actions[bot]@users.noreply.github.com"

      - name: Add upstream remote
        run: |
          git remote add upstream https://github.com/knighthat/Kreate.git
          git fetch upstream

      - name: Merge upstream but skip workflows
        run: |
          git checkout main
          git merge --no-commit --no-ff upstream/main || true
          git rm -r --cached .github/workflows || true
          rm -rf .github/workflows
          git commit -m "Sync with upstream (excluding workflows)" || true

      - name: Push changes
        run: |
          git push origin main
